stages:
  generate-raw-data:
    cmd: uv run python -m src.dummy_data.generate --output data/raw/
    deps:
    - src/dummy_data/generate.py
    outs:
    - data/raw/data_0.csv
    - data/raw/data_1.csv
    - data/raw/data_2.csv
    - data/raw/data_3.csv
    - data/raw/data_4.csv
  preprocess-data:
    foreach: ${runs}
    do:
      cmd: uv run python -m src.dummy_data.preprocess --input data/raw/${item}.csv --output data/preprocessed/
      deps:
      - src/dummy_data/preprocess.py
      - data/raw/${item}.csv
      outs:
      - data/preprocessed/${item}.parquet
