stages:
  build_image:
    cmd:
    - podman build -t ${image_name} .
    - podman images --no-trunc --quiet ${image_name} > image.sha
    deps:
    - src
    - pyproject.toml
    - uv.lock
    - Dockerfile
    outs:
    - image.sha:
        cache: false
  generate_raw_data:
    cmd: podman run --rm -v ./data/raw:/raw:z ${image_name} src.dummy_data.generate
      --output /raw
    deps:
    - image.sha
    outs:
    - data/raw:
        persist: true
  preprocess_data:
    foreach: ${runs}
    do:
      cmd: podman run --rm -v ./data/raw:/raw:z -v ./data/preprocessed:/preprocessed:z
        ${image_name} src.dummy_data.preprocess --input /raw/${item}.csv --output
        /preprocessed
      deps:
      - image.sha
      - data/raw/${item}.csv
      outs:
      - data/preprocessed/${item}.parquet
